BUY_LEAD = {
    "branch": "YMCA",
    "mobile": "9876543210",
    "alternateMobile": "9123456780",
    "source": "Website",
    "mode": "Home",
    "brokerName": "",
    "category": "Individual",
    "customerName": "Rahul Sharma",
    "ownerName": "Rahul Sharma",
    "paymentName": "Rahul Sharma",
    "leadAddress": {
        "address": "test address",
        "state": "Gujarat",
        "city": "Ahmedabad",
        "area": "test area",
        "pincode": 123456,
    },
    "makeId": 1,
    "modelId": 2,
    "variant": "",
    "color": "",
    "fuelType": "Petrol",
    "mfgMonth": "January",
    "mfgYear": "2022",
    "kms": 35000,
    "owner": "1",
    "clientOffer": 500000,
    "ourOffer": 480000,
    "telecaller": "tele",
    "executive": "exe",
    "remarks": "Customer wants urgent deal",
}

UPDATE_LEAD = {
    "branch": "YMCA",
    "alternateMobile": "90855484515",
    "source": "Website",
    "brokerName": "",
    "customerName": "Vishal Mehta",
    "leadAddress": {
        "address": "Updated address",
        "state": "Gujarat",
        "city": "Ahmedabad",
        "area": "test area",
        "pincode": 654321,
    },
    "makeId": 1,
    "modelId": 2,
    "variant": "",
    "color": "",
    "fuelType": "Petrol",
    "mfg_month": "January",
    "mfg_year": "2022",
    "kms": 35000,
    "owner": "1",
    "clientOffer": 500000,
    "ourOffer": 480000,
    "remarks": "Update customer wants urgent deal",
}

BUY_LEAD_ALLOCATION = {
    "leadIds": [1, 2, 3],
    "telecaller": "tele",
    "executive": "exe",
}

BUY_LEAD_FOLLOWUP = {
    "branch": "YMCA",
    "customerName": "Rahul Sharma",
    "alternateMobile": "9123456780",
    "mode": "Home",
    "source": "Website",
    "brokerName": "",
    "leadAddress": {
        "address": "test address",
        "state": "Gujarat",
        "city": "Ahmedabad",
        "area": "test area",
        "pincode": 123456,
    },
    "makeId": 1,
    "modelId": 2,
    "variant": "",
    "color": "",
    "fuelType": "Petrol",
    "mfg_month": "January",
    "mfg_year": "2022",
    "kms": 35000,
    "owner": "1",
    "clientOffer": 500000,
    "ourOffer": 480000,
    "telecaller": "tele",
    "executive": "exe",
    "leadFollowup": {
        "stage": "Appointment",
        "disposition": "Appointment",
        "calldate": "2026-04-03T18:30:00.000",
        "preferredTime": "09:00 AM to 10:00 AM",
        "notes": "Customer wants urgent deal",
    },
}

BUY_LEAD_PAYMENT = {
    "refurbCost": 25000.00,
    "deal": 500000.00,
    "serviceCharge": 10000.00,
    "tcs": 5000.00,
    "gst": 1800.00,
    "tax": 1200.00,
    "rcd": 3000.00,
    "commission": 15000.00,
    "dealWithCommission": 515000.00,
    "dealWithoutCommission": 500000.00,
    "token": 25000.00,
    "cash": 100000.00,
    "loan": 350000.00,
    "less": 5000.00,
    "hold": 10000.00,
    "chRtgs": 400000.00,
    "totalPayble": 485000.00,
    "remarks": "Payment details added for purchase lead",
    "leadVehicle": {
        "registrationNo": "GJ01AB1234",
        "transmission": "Manual",
        "chassisNo": "CHS123456789",
        "engineNo": "ENG123456789",
        "cubicCapacity": 1197,
        "pushButton": "No",
        "regMonth": "January",
        "regYear": "2022",
        "euro": "BS6",
        "rcBook": "Yes",
        "secondKey": "Yes",
        "hypo": "No",
        "hypoBank": "NA",
        "serviceRecord": "Yes",
        "puc": "Yes",
        "memo": "No",
        "memoAmount": 0.00,
        "memoPaid": "US",
        "mvTax": 0.00,
        "rma": "No",
        "taxiPrivate": "Private",
        "otherNoc": "No",
        "blacklist": "No",
        "rtoStatus": "Clear",
    },
    "leadVehicleInsurance": {
        "onlineInsurance": "Yes",
        "insuranceType": "CPTP",
        "cpZdCompany": "HDFC Ergo",
        "tpCompany": "HDFC Ergo",
        "cpZdDate": "2026-12-31T00:00:00.000",
        "tpDate": "2027-12-31T00:00:00.000",
        "idv": 450000.00,
        "ncb": 20.00,
        "premium": 15000.00,
    },
}

BUY_LEAD_TARGET = {
    "user_name": "john.doe",
    "month": "June",
    "year": "2026",
    "normal": 40,
    "premium": 10,
    "total": 50,
}
