BUY_LEAD = {
    "mobile": "9876543210",
    "alternateMobile": "9123456780",
    "source": "Website",
    "mode": "Home",
    "brokerName": "ABC Brokers",
    "customerName": "Rahul Sharma",
    "makeId": 1,
    "modelId": 2,
    "variant": "ZXI Plus",
    "color": "White",
    "fuelType": "Petrol",
    "year": "2022",
    "kms": 35000,
    "owner": "1",
    "clientOffer": 500000,
    "ourOffer": 480000,
    "telecaller": "Priya",
    "executive": "Amit",
    "remarks": "Customer wants urgent deal",
}
