BUY_LEAD = {
    "branch": "YMCA",
    "mobile": "9876543210",
    "alternateMobile": "9123456780",
    "source": "Website",
    "mode": "Home",
    "brokerName": "",
    "customerName": "Rahul Sharma",
    "leadAddress":{
        "address" : "test address",
        "state": "Gujarat",
        "city": "Ahmedabad",
        "area": "test area",
        "pincode": 123456,
    },
    "makeId": 1,
    "modelId": 2,
    "variant": "",
    "color": "",
    "fuelType": "Petrol",
    "year": "2022",
    "kms": 35000,
    "owner": "1",
    "clientOffer": 500000,
    "ourOffer": 480000,
    "telecaller": "tele",
    "executive": "exe",
    "remarks": "Customer wants urgent deal",
}

UPDATE_LEAD = {
    "branch": "YMCA",
    "alternateMobile": "90855484515",
    "source": "Website",
    "brokerName": "",
    "customerName": "Vishal Mehta",
    "leadAddress":{
        "address" : "Updated address",
        "state": "Gujarat",
        "city": "Ahmedabad",
        "area": "test area",
        "pincode": 654321,
    },
    "makeId": 1,
    "modelId": 2,
    "variant": "",
    "color": "",
    "fuelType": "Petrol",
    "year": "2022",
    "kms": 35000,
    "owner": "1",
    "clientOffer": 500000,
    "ourOffer": 480000,
    "remarks": "Update customer wants urgent deal",
}

BUY_LEAD_ALLOCATION = {
    "leadIds":[1,2,3],
    "telecaller": "tele",
    "executive": "exe",
}

BUY_LEAD_FOLLOWUP = {
    "branch": "YMCA",
    "customerName": "Rahul Sharma",
    "alternateMobile": "9123456780",
    "mode": "Home",
    "source": "Website",
    "brokerName": "",
    "leadAddress":{
        "address" : "test address",
        "state": "Gujarat",
        "city": "Ahmedabad",
        "area": "test area",
        "pincode": 123456,
    },
    "makeId": 1,
    "modelId": 2,
    "variant": "",
    "color": "",
    "fuelType": "Petrol",
    "year": "2022",
    "kms": 35000,
    "owner": "1",
    "clientOffer": 500000,
    "ourOffer": 480000,
    "telecaller": "tele",
    "executive": "exe",
    "leadFollowup":{
        "stage": "Appointment",
        "disposition": "Appointment",
        "calldate": "06/04/2026",
        "preferredTime":"09:00 AM to 10:00 AM",
        "notes": "Customer wants urgent deal",
    },
}