from orm.buy.buy import (
    tblbuylead,
    tblbuylead_address,
    tblbuylead_evaluation,
    tblbuylead_file,
    tblbuylead_followup,
    tblbuylead_payment,
    tblbuylead_vehicle,
    tblbuylead_vehicle_insurance,
)
from orm.common.common import mstmake, mstmodel

LEAD_SEARCHABLE_COLUMNS = {
    "branch": tblbuylead.c.branch,
    "mobile": tblbuylead.c.mobile,
    "source": tblbuylead.c.source,
    "mode": tblbuylead.c.mode,
    "broker_name": tblbuylead.c.broker_name,
    "customer_name": tblbuylead.c.customer_name,
    "make": mstmake.c.make,
    "model": mstmodel.c.model,
    "fuel_type": tblbuylead.c.fuel_type,
    "mfg_year": tblbuylead.c.mfg_year,
    "kms": tblbuylead.c.kms,
    "owner": tblbuylead.c.owner,
    "status": tblbuylead.c.status,
    "telecaller": tblbuylead.c.telecaller,
    "executive": tblbuylead.c.executive,
}

LEAD_SORTABLE_COLUMNS = {
    "id": tblbuylead.c.id,
    "mobile": tblbuylead.c.mobile,
    "source": tblbuylead.c.source,
    "mode": tblbuylead.c.mode,
    "make": mstmake.c.make,
    "model": mstmodel.c.model,
}

LEAD_COLUMNS = [
    tblbuylead.c.id,
    tblbuylead.c.status,
    tblbuylead.c.mobile,
    tblbuylead.c.alternate_mobile,
    tblbuylead.c.customer_name,
    tblbuylead_followup.c.stage,
    tblbuylead_followup.c.disposition,
    tblbuylead_followup.c.calldate,
    tblbuylead_followup.c.preferred_time,
    tblbuylead_followup.c.notes,
    tblbuylead.c.branch,
    tblbuylead.c.source,
    tblbuylead.c.mode,
    tblbuylead.c.broker_name,
    tblbuylead.c.category,
    tblbuylead.c.owner_name,
    tblbuylead.c.payment_name,
    tblbuylead.c.make_id,
    tblbuylead.c.model_id,
    mstmake.c.make,
    mstmodel.c.model,
    tblbuylead.c.variant,
    tblbuylead.c.color,
    tblbuylead.c.fuel_type,
    tblbuylead.c.mfg_month,
    tblbuylead.c.mfg_year,
    tblbuylead.c.kms,
    tblbuylead.c.owner,
    tblbuylead.c.client_offer,
    tblbuylead.c.our_offer,
    tblbuylead.c.telecaller,
    tblbuylead.c.executive,
    tblbuylead.c.allocated_at,
    tblbuylead.c.allocated_by,
    tblbuylead.c.created_at,
    tblbuylead.c.created_by,
    tblbuylead.c.remarks,
    tblbuylead_address.c.address,
    tblbuylead_address.c.state,
    tblbuylead_address.c.city,
    tblbuylead_address.c.area,
    tblbuylead_address.c.pincode,
    tblbuylead_followup.c.created_at.label("followupCreatedAt"),
    tblbuylead_followup.c.created_by.label("followupCreatedBy"),
]

FOLLOWUP_LEAD_SEARCHABLE_COLUMNS = {
    "branch": tblbuylead.c.branch,
    "mobile": tblbuylead.c.mobile,
    "source": tblbuylead.c.source,
    "mode": tblbuylead.c.mode,
    "broker_name": tblbuylead.c.broker_name,
    "customer_name": tblbuylead.c.customer_name,
    "make": mstmake.c.make,
    "model": mstmodel.c.model,
    "fuel_type": tblbuylead.c.fuel_type,
    "mfg_year": tblbuylead.c.mfg_year,
    "kms": tblbuylead.c.kms,
    "owner": tblbuylead.c.owner,
    "status": tblbuylead.c.status,
    "telecaller": tblbuylead.c.telecaller,
    "executive": tblbuylead.c.executive,
    "stage": tblbuylead_followup.c.stage,
    "disposition": tblbuylead_followup.c.disposition,
}

FOLLOWUP_LEAD_COLUMNS = [
    tblbuylead.c.id,
    tblbuylead.c.status,
    tblbuylead.c.mobile,
    tblbuylead.c.alternate_mobile,
    tblbuylead.c.customer_name,
    tblbuylead_followup.c.stage,
    tblbuylead_followup.c.disposition,
    tblbuylead_followup.c.calldate,
    tblbuylead_followup.c.preferred_time,
    tblbuylead_followup.c.notes,
    tblbuylead.c.branch,
    tblbuylead.c.source,
    tblbuylead.c.mode,
    tblbuylead.c.broker_name,
    tblbuylead.c.make_id,
    tblbuylead.c.model_id,
    mstmake.c.make,
    mstmodel.c.model,
    tblbuylead.c.variant,
    tblbuylead.c.color,
    tblbuylead.c.fuel_type,
    tblbuylead.c.mfg_month,
    tblbuylead.c.mfg_year,
    tblbuylead.c.kms,
    tblbuylead.c.owner,
    tblbuylead.c.client_offer,
    tblbuylead.c.our_offer,
    tblbuylead.c.telecaller,
    tblbuylead.c.executive,
    tblbuylead.c.allocated_at,
    tblbuylead.c.allocated_by,
    tblbuylead.c.created_at,
    tblbuylead.c.created_by,
    tblbuylead.c.remarks,
    tblbuylead_address.c.address,
    tblbuylead_address.c.state,
    tblbuylead_address.c.city,
    tblbuylead_address.c.area,
    tblbuylead_address.c.pincode,
    tblbuylead_followup.c.created_at.label("followupCreatedAt"),
    tblbuylead_followup.c.created_by.label("followupCreatedBy"),
]

IMPORT_LEAD_COLUMNS = [
    tblbuylead_file.c.id,
    tblbuylead_file.c.s3_key,
    tblbuylead_file.c.file_status,
    tblbuylead_file.c.file_uuid,
    tblbuylead_file.c.processed_records,
    tblbuylead_file.c.error_records,
    tblbuylead_file.c.error_s3_key,
    tblbuylead_file.c.created_at,
    tblbuylead_file.c.created_by,
]

IMPORT_LEAD_SEARCHABLE_COLUMNS = {
    "s3_key": tblbuylead.c.branch,
    "file_status": tblbuylead.c.mobile,
    "file_uuid": tblbuylead.c.source,
    "error_s3_key": tblbuylead_file.c.error_s3_key,
}

LEAD_PAYMENT_PDF_COLUMNS = [
    tblbuylead.c.id.label("lead_id"),
    tblbuylead.c.status,
    tblbuylead.c.branch,
    tblbuylead.c.mobile,
    tblbuylead.c.alternate_mobile,
    tblbuylead.c.source,
    tblbuylead.c.mode,
    tblbuylead.c.broker_name,
    tblbuylead.c.customer_name,
    tblbuylead.c.owner_name,
    tblbuylead.c.payment_name,
    mstmake.c.make,
    mstmodel.c.model,
    tblbuylead.c.variant,
    tblbuylead.c.color,
    tblbuylead.c.fuel_type,
    tblbuylead.c.mfg_month,
    tblbuylead.c.mfg_year,
    tblbuylead.c.kms,
    tblbuylead.c.owner,
    tblbuylead.c.client_offer,
    tblbuylead.c.our_offer,
    tblbuylead.c.telecaller,
    tblbuylead.c.executive,
    tblbuylead.c.remarks.label("lead_remarks"),
    tblbuylead_payment.c.id.label("payment_id"),
    tblbuylead_payment.c.refurb_cost,
    tblbuylead_payment.c.deal,
    tblbuylead_payment.c.service_charge,
    tblbuylead_payment.c.tcs,
    tblbuylead_payment.c.gst,
    tblbuylead_payment.c.tax,
    tblbuylead_payment.c.rcd,
    tblbuylead_payment.c.commission,
    tblbuylead_payment.c.deal_with_commission,
    tblbuylead_payment.c.deal_without_commission,
    tblbuylead_payment.c.token,
    tblbuylead_payment.c.cash,
    tblbuylead_payment.c.loan,
    tblbuylead_payment.c.less,
    tblbuylead_payment.c.hold,
    tblbuylead_payment.c.ch_rtgs,
    tblbuylead_payment.c.total_payble,
    tblbuylead_payment.c.remarks.label("payment_remarks"),
    tblbuylead_payment.c.created_at.label("payment_created_at"),
    tblbuylead_payment.c.created_by.label("payment_created_by"),
    tblbuylead_payment.c.modified_at.label("payment_modified_at"),
    tblbuylead_payment.c.modified_by.label("payment_modified_by"),
    tblbuylead_vehicle.c.registration_no,
    tblbuylead_vehicle.c.transmission,
    tblbuylead_vehicle.c.cubic_capacity,
    tblbuylead_vehicle.c.chassis_no,
    tblbuylead_vehicle.c.engine_no,
    tblbuylead_vehicle.c.push_button,
    tblbuylead_vehicle.c.company_invoice,
    tblbuylead_vehicle.c.noc,
    tblbuylead_vehicle.c.reg_month,
    tblbuylead_vehicle.c.reg_year,
    tblbuylead_vehicle.c.euro,
    tblbuylead_vehicle.c.rc_book,
    tblbuylead_vehicle.c.second_key,
    tblbuylead_vehicle.c.hypo,
    tblbuylead_vehicle.c.hypo_bank,
    tblbuylead_vehicle.c.service_record,
    tblbuylead_vehicle.c.puc,
    tblbuylead_vehicle.c.memo,
    tblbuylead_vehicle.c.memo_amount,
    tblbuylead_vehicle.c.memo_paid,
    tblbuylead_vehicle.c.mv_tax,
    tblbuylead_vehicle.c.rma,
    tblbuylead_vehicle.c.taxi_private,
    tblbuylead_vehicle.c.other_noc,
    tblbuylead_vehicle.c.blacklist,
    tblbuylead_vehicle.c.rto_status,
    tblbuylead_vehicle_insurance.c.online_insurance,
    tblbuylead_vehicle_insurance.c.insurance_type,
    tblbuylead_vehicle_insurance.c.cp_zd_company,
    tblbuylead_vehicle_insurance.c.tp_company,
    tblbuylead_vehicle_insurance.c.cp_zd_date,
    tblbuylead_vehicle_insurance.c.tp_date,
    tblbuylead_vehicle_insurance.c.idv,
    tblbuylead_vehicle_insurance.c.ncb,
    tblbuylead_vehicle_insurance.c.premium,
]

LEAD_EVALUATION_PDF_COLUMNS = [
    tblbuylead.c.id.label("lead_id"),
    tblbuylead.c.status,
    tblbuylead.c.branch,
    tblbuylead.c.mobile,
    tblbuylead.c.alternate_mobile,
    tblbuylead.c.source,
    tblbuylead.c.mode,
    tblbuylead.c.broker_name,
    tblbuylead.c.customer_name,
    tblbuylead.c.owner_name,
    tblbuylead.c.payment_name,
    mstmake.c.make,
    mstmodel.c.model,
    tblbuylead.c.variant,
    tblbuylead.c.color,
    tblbuylead.c.fuel_type,
    tblbuylead.c.mfg_month,
    tblbuylead.c.mfg_year,
    tblbuylead.c.kms,
    tblbuylead.c.owner,
    tblbuylead.c.client_offer,
    tblbuylead.c.our_offer,
    tblbuylead.c.telecaller,
    tblbuylead.c.executive,
    tblbuylead.c.remarks.label("lead_remarks"),
    tblbuylead_evaluation.c.id.label("evaluation_id"),
    tblbuylead_evaluation.c.remarks.label("evaluation_remarks"),
    tblbuylead_evaluation.c.created_at.label("evaluation_created_at"),
    tblbuylead_evaluation.c.created_by.label("evaluation_created_by"),
    tblbuylead_evaluation.c.modified_at.label("evaluation_modified_at"),
    tblbuylead_evaluation.c.modified_by.label("evaluation_modified_by"),
    tblbuylead_vehicle.c.registration_no,
    tblbuylead_vehicle.c.transmission,
    tblbuylead_vehicle.c.cubic_capacity,
    tblbuylead_vehicle.c.chassis_no,
    tblbuylead_vehicle.c.engine_no,
    tblbuylead_vehicle.c.push_button,
    tblbuylead_vehicle.c.company_invoice,
    tblbuylead_vehicle.c.noc,
    tblbuylead_vehicle.c.reg_month,
    tblbuylead_vehicle.c.reg_year,
    tblbuylead_vehicle.c.euro,
    tblbuylead_vehicle.c.rc_book,
    tblbuylead_vehicle.c.second_key,
    tblbuylead_vehicle.c.hypo,
    tblbuylead_vehicle.c.hypo_bank,
    tblbuylead_vehicle.c.service_record,
    tblbuylead_vehicle.c.puc,
    tblbuylead_vehicle.c.memo,
    tblbuylead_vehicle.c.memo_amount,
    tblbuylead_vehicle.c.memo_paid,
    tblbuylead_vehicle.c.mv_tax,
    tblbuylead_vehicle.c.rma,
    tblbuylead_vehicle.c.taxi_private,
    tblbuylead_vehicle.c.other_noc,
    tblbuylead_vehicle.c.blacklist,
    tblbuylead_vehicle.c.rto_status,
    tblbuylead_vehicle_insurance.c.online_insurance,
    tblbuylead_vehicle_insurance.c.insurance_type,
    tblbuylead_vehicle_insurance.c.cp_zd_company,
    tblbuylead_vehicle_insurance.c.tp_company,
    tblbuylead_vehicle_insurance.c.cp_zd_date,
    tblbuylead_vehicle_insurance.c.tp_date,
    tblbuylead_vehicle_insurance.c.idv,
    tblbuylead_vehicle_insurance.c.ncb,
    tblbuylead_vehicle_insurance.c.premium,
]
