from orm.buy.buy import (
    tblbuylead,
    tblbuylead_address,
    tblbuylead_file,
    tblbuylead_followup,
)
from orm.common.common import mstmake, mstmodel

LEAD_SEARCHABLE_COLUMNS = {
    "branch": tblbuylead.c.branch,
    "mobile": tblbuylead.c.mobile,
    "source": tblbuylead.c.source,
    "mode": tblbuylead.c.mode,
    "broker_name": tblbuylead.c.broker_name,
    "customer_name": tblbuylead.c.customer_name,
    "make": mstmake.c.make,
    "model": mstmodel.c.model,
    "fuel_type": tblbuylead.c.fuel_type,
    "mfg_year": tblbuylead.c.mfg_year,
    "kms": tblbuylead.c.kms,
    "owner": tblbuylead.c.owner,
    "status": tblbuylead.c.status,
    "telecaller": tblbuylead.c.telecaller,
    "executive": tblbuylead.c.executive,
}

LEAD_SORTABLE_COLUMNS = {
    "id": tblbuylead.c.id,
    "mobile": tblbuylead.c.mobile,
    "source": tblbuylead.c.source,
    "mode": tblbuylead.c.mode,
    "make": mstmake.c.make,
    "model": mstmodel.c.model,
}

LEAD_COLUMNS = [
    tblbuylead.c.id,
    tblbuylead.c.status,
    tblbuylead.c.mobile,
    tblbuylead.c.alternate_mobile,
    tblbuylead.c.customer_name,
    tblbuylead_followup.c.stage,
    tblbuylead_followup.c.disposition,
    tblbuylead_followup.c.calldate,
    tblbuylead_followup.c.preferred_time,
    tblbuylead_followup.c.notes,
    tblbuylead.c.branch,
    tblbuylead.c.source,
    tblbuylead.c.mode,
    tblbuylead.c.broker_name,
    tblbuylead.c.category,
    tblbuylead.c.owner_name,
    tblbuylead.c.payment_name,
    tblbuylead.c.make_id,
    tblbuylead.c.model_id,
    mstmake.c.make,
    mstmodel.c.model,
    tblbuylead.c.variant,
    tblbuylead.c.color,
    tblbuylead.c.fuel_type,
    tblbuylead.c.mfg_month,
    tblbuylead.c.mfg_year,
    tblbuylead.c.kms,
    tblbuylead.c.owner,
    tblbuylead.c.client_offer,
    tblbuylead.c.our_offer,
    tblbuylead.c.telecaller,
    tblbuylead.c.executive,
    tblbuylead.c.allocated_at,
    tblbuylead.c.allocated_by,
    tblbuylead.c.created_at,
    tblbuylead.c.created_by,
    tblbuylead.c.remarks,
    tblbuylead_address.c.address,
    tblbuylead_address.c.state,
    tblbuylead_address.c.city,
    tblbuylead_address.c.area,
    tblbuylead_address.c.pincode,
    tblbuylead_followup.c.created_at.label("followupCreatedAt"),
    tblbuylead_followup.c.created_by.label("followupCreatedBy"),
]

FOLLOWUP_LEAD_SEARCHABLE_COLUMNS = {
    "branch": tblbuylead.c.branch,
    "mobile": tblbuylead.c.mobile,
    "source": tblbuylead.c.source,
    "mode": tblbuylead.c.mode,
    "broker_name": tblbuylead.c.broker_name,
    "customer_name": tblbuylead.c.customer_name,
    "make": mstmake.c.make,
    "model": mstmodel.c.model,
    "fuel_type": tblbuylead.c.fuel_type,
    "mfg_year": tblbuylead.c.mfg_year,
    "kms": tblbuylead.c.kms,
    "owner": tblbuylead.c.owner,
    "status": tblbuylead.c.status,
    "telecaller": tblbuylead.c.telecaller,
    "executive": tblbuylead.c.executive,
    "stage": tblbuylead_followup.c.stage,
    "disposition": tblbuylead_followup.c.disposition,
}

FOLLOWUP_LEAD_COLUMNS = [
    tblbuylead.c.id,
    tblbuylead.c.status,
    tblbuylead.c.mobile,
    tblbuylead.c.alternate_mobile,
    tblbuylead.c.customer_name,
    tblbuylead_followup.c.stage,
    tblbuylead_followup.c.disposition,
    tblbuylead_followup.c.calldate,
    tblbuylead_followup.c.preferred_time,
    tblbuylead_followup.c.notes,
    tblbuylead.c.branch,
    tblbuylead.c.source,
    tblbuylead.c.mode,
    tblbuylead.c.broker_name,
    tblbuylead.c.make_id,
    tblbuylead.c.model_id,
    mstmake.c.make,
    mstmodel.c.model,
    tblbuylead.c.variant,
    tblbuylead.c.color,
    tblbuylead.c.fuel_type,
    tblbuylead.c.mfg_month,
    tblbuylead.c.mfg_year,
    tblbuylead.c.kms,
    tblbuylead.c.owner,
    tblbuylead.c.client_offer,
    tblbuylead.c.our_offer,
    tblbuylead.c.telecaller,
    tblbuylead.c.executive,
    tblbuylead.c.allocated_at,
    tblbuylead.c.allocated_by,
    tblbuylead.c.created_at,
    tblbuylead.c.created_by,
    tblbuylead.c.remarks,
    tblbuylead_address.c.address,
    tblbuylead_address.c.state,
    tblbuylead_address.c.city,
    tblbuylead_address.c.area,
    tblbuylead_address.c.pincode,
    tblbuylead_followup.c.created_at.label("followupCreatedAt"),
    tblbuylead_followup.c.created_by.label("followupCreatedBy"),
]

IMPORT_LEAD_COLUMNS = [
    tblbuylead_file.c.id,
    tblbuylead_file.c.s3_key,
    tblbuylead_file.c.file_status,
    tblbuylead_file.c.file_uuid,
    tblbuylead_file.c.processed_records,
    tblbuylead_file.c.error_records,
    tblbuylead_file.c.error_s3_key,
    tblbuylead_file.c.created_at,
    tblbuylead_file.c.created_by,
]

IMPORT_LEAD_SEARCHABLE_COLUMNS = {
    "s3_key": tblbuylead.c.branch,
    "file_status": tblbuylead.c.mobile,
    "file_uuid": tblbuylead.c.source,
    "error_s3_key": tblbuylead_file.c.error_s3_key,
}
