class AuthException(Exception): ...


class Unauthorized(AuthException): ...


class ForbiddenError(AuthException): ...


class NotFound(AuthException): ...


class CreationError(Exception): ...

class AllocationError(Exception): ...
